project:
  type: website

website:
  title: "Frank Shih"
  description: "Postdoctoral Research Scholar, MSKCC | Uncertainty Quantification, Deep Learning, Reinforcement Learning, High-Dimensional Inference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: news/
        text: News
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/FrankShih0807
      - icon: envelope
        href: mailto:shihf@mskcc.org

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



